version: 2
jobs:
  build:
    docker:
      - image: athos/cljs-dev:openjdk-8-alpine-20190219-0

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
      CHROMIUM_BIN: /usr/bin/chromium-browser

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: restore npm cache
          key: v1-npm-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          name: save npm cache
          paths:
            - ~/.npm
          key: v1-npm-{{ checksum "package-lock.json" }}

      - restore_cache:
          name: restore clj cache
          key: v1-clj-{{ checksum "project.clj" }}

      - run: lein deps

      - save_cache:
          name: save clj cache
          paths:
            - ~/.m2
          key: v1-clj-{{ checksum "project.clj" }}

      - run:
          name: browser test
          command: lein doo chromium-headless test once

      - run:
          name: browser min test
          command: lein doo chromium-headless min-test once

      - run:
          name: node test
          command: lein doo node node-test once

      # - run:
      #     name: code-coverage
      #     command: |
      #       CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov
      #       bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
